services:
  ai_service:
    container_name: ai_service_container
    image: moha2001/ai_service:latest
    depends_on:
      - web
    ports:
      - ${DROWSINESS_SERVICE_PORT}:80
    environment:
      - APP_PORT=80
      - CONF_VAR=0.2
      - SLEEP_TIME_ALERT=4

  web:
    build: .
    image: drivo_plus:0.1.1
    container_name: drivo_plus-web
    ports:
      - ${PORT_NUMBER}:80
    develop:
      watch:
        - action: restart
          path: .
          target: /app
